#!/bin/bash

# (The MIT license)
#
# Copyright (c) 2015 tsukurite
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to
# deal in the Software without restriction, including without limitation the
# rights to use, copy, modify, merge, publish, distribute, sublicense, and/or
# sell copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
# FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
# IN THE SOFTWARE.

# for debug
#set -x

set -u

__git_package_main() {
  git rev-parse >/dev/null 2>&1
  if [ "$?" -ne 0 ]
  then
    echo 'git-pakcage must execute inside git repository.' 1>&2
    exit 1
  fi

  # for loop variable
  local target=

  # target directory name
  local dir=
  # target file name
  local file=

  # repository root
  local root=$(git rev-parse --show-toplevel)
  # destination directory
  local destination=$(mktemp -d XXXXXXXX)

  for target in $(git log --name-only --pretty=format: $@ | sort -u)
  do
    # continue if file is not exists
    if [ ! -e "$root/$target" ]
    then
      continue
    fi

    dir=$(dirname "$target")
    file=$(basename "$target")

    # copy, it equals to `cp -a --parents`
    mkdir -p "$destination/$dir"
    cp -a "$root/$target" "$destination/$dir/$file"
  done

  echo "packaged to $destination"
}

__git_package_main "$@"
